// <auto-generated />
using System;
using IT_Conference_Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IT_Conference_Service.Migrations
{
    [DbContext(typeof(ConferenceDbContext))]
    partial class ConferenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IT_Conference_Service.Data.Entitiess.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_info_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("sent_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationInfoId")
                        .IsUnique();

                    b.ToTable("applications");
                });

            modelBuilder.Entity("IT_Conference_Service.Data.Entitiess.ApplicationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("activity_name");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int")
                        .HasColumnName("activity_type");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Outline")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("outline");

                    b.HasKey("Id");

                    b.ToTable("application_info");
                });

            modelBuilder.Entity("IT_Conference_Service.Data.Entitiess.Application", b =>
                {
                    b.HasOne("IT_Conference_Service.Data.Entitiess.ApplicationInfo", "ApplicationInfo")
                        .WithOne("Application")
                        .HasForeignKey("IT_Conference_Service.Data.Entitiess.Application", "ApplicationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationInfo");
                });

            modelBuilder.Entity("IT_Conference_Service.Data.Entitiess.ApplicationInfo", b =>
                {
                    b.Navigation("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
